var htmlText = '<div id="menuButton" style="display:none;">Open Menu</div>';
htmlText += '<span id="hiddenMenu">';
htmlText += '<ul>';

// Preface
htmlText += '	<li><a STYLE="text-decoration: none;" href="//www.probabilitycourse.com/preface.php">0 Preface</a>';
htmlText += '	</li>';
//chapter 1
htmlText += '	<li><a>1 Basic Concepts</a>';
htmlText += '	<ul>';
htmlText += '		<li><a style="text-decoration: none;" href=//www.probabilitycourse.com/chapter1/1_0_0_introduction.php>1.0 Introduction</a>';
htmlText += '		</li>';
htmlText += '		<li><a>1.1 Introduction</a>';
htmlText += '		<ul>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter1/1_1_0_what_is_probability.php">1.1.0 What Is Probability?</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter1/1_1_1_example.php">1.1.1 Example</a></li>';
htmlText += '		</ul>';
htmlText += '		</li>';
htmlText += '		<li><a>1.2 Review of Set Theory</a>';
htmlText += '		<ul>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter1/1_2_0_review_set_theory.php">1.2.0 Review</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter1/1_2_1_venn.php">1.2.1 Venn Diagrams</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter1/1_2_2_set_operations.php">1.2.2 Set Operations</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter1/1_2_3_cardinality.php">1.2.3 Cardinality</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter1/1_2_4_functions.php">1.2.4 Functions</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter1/1_2_5_solved1.php">1.2.5 Solved Problems</a></li>';
htmlText += '		</ul>';
htmlText += '		</li>';
htmlText += '		<li><a>1.3 Random Experiments and Probabilities</a>';
htmlText += '		<ul>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter1/1_3_1_random_experiments.php">1.3.1 Random Experiments</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter1/1_3_2_probability.php">1.3.2 Probability</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter1/1_3_3_finding_probabilities.php">1.3.3 Finding Probabilities</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter1/1_3_4_discrete_models.php">1.3.4 Discrete Models</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter1/1_3_5_continuous_models.php">1.3.5 Continuous Models</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter1/1_3_6_solved2.php">1.3.6 Solved Problems</a></li>';
htmlText += '		</ul>';
htmlText += '		</li>';
htmlText += '		<li><a>1.4 Conditional Probability</a>';
htmlText += '		<ul>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter1/1_4_0_conditional_probability.php">1.4.0 Conditional Probability</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter1/1_4_1_independence.php">1.4.1 Independence</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter1/1_4_2_total_probability.php">1.4.2 Law of Total Probability</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter1/1_4_3_bayes_rule.php">1.4.3 Bayes\' Rule</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter1/1_4_4_conditional_independence.php">1.4.4 Conditional Independence</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter1/1_4_5_solved3.php">1.4.5 Solved Problems</a></li>';
htmlText += '		</ul>';
htmlText += '		</li>';
htmlText += '		<li><a>1.5 Problems</a>';
htmlText += '		<ul>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter1/1_5_0_chapter1_problems.php">1.5.0 End of Chapter Problems</a></li>';
htmlText += '		</ul>';
htmlText += '		</li>';
htmlText += '	</ul>';
htmlText += '	</li>';
htmlText += '	<li><a>2 Combinatorics: Counting Methods</a>';
htmlText += '	<ul>';
htmlText += '		<li><a>2.1 Combinatorics</a>';
htmlText += '		<ul>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter2/2_1_0_counting.php">2.1.0 Finding Probabilities with Counting Methods</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter2/2_1_1_ordered_with_replacement.php">2.1.1 Ordered with Replacement</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter2/2_1_2_ordered_without_replacement.php">2.1.2 Ordered without Replacement</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter2/2_1_3_unordered_without_replacement.php">2.1.3 Unordered without Replacement</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter2/2_1_4_unordered_with_replacement.php">2.1.4 Unordered with Replacement</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter2/2_1_5_solved2_1.php">2.1.5 Solved Problems</a></li>';
htmlText += '		</ul>';
htmlText += '		</li>';
/*
htmlText += '		<li><a>2.2 Recursions</a>';
htmlText += '		<ul>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter2/2_2_0_using_recursion.php">2.2.0 Using Recursion</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter2/2_2_1_linear_homogeneous.php">2.2.1 Linear Homogeneous Recurrence Equations</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter2/2_2_2_recursion_with_conditioning.php">2.2.2 Recursion with Conditioning</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter2/2_2_3_solved2_2.php">2.2.3 Solved Problems</a></li>';
htmlText += '		</ul>';
htmlText += '		</li>';
*/
htmlText += '		<li><a>2.2 Problems</a>';
htmlText += '		<ul>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter2/2_3_0_chapter2_problems.php">2.2.0 End of Chapter Problems</a></li>';
htmlText += '		</ul>';
htmlText += '		</li>';
htmlText += '	</ul>';
htmlText += '	</li>';
htmlText += '	<li><a>3 Discrete Random Variables</a>';
htmlText += '	<ul>';
htmlText += '		<li><a>3.1 Basic Concepts</a>';
htmlText += '		<ul>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter3/3_1_1_random_variables.php">3.1.1 Random Variables</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter3/3_1_2_discrete_random_var.php">3.1.2 Discrete Random Variables</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter3/3_1_3_pmf.php">3.1.3 Probability Mass Function</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter3/3_1_4_independent_random_var.php">3.1.4 Independent Random Variables</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter3/3_1_5_special_discrete_distr.php">3.1.5 Special Distributions</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter3/3_1_6_solved3_1.php">3.1.6 Solved Problems</a></li>';
htmlText += '		</ul>';
htmlText += '		</li>';
htmlText += '		<li><a>3.2 More about Discrete Random Variables</a>';
htmlText += '		<ul>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter3/3_2_1_cdf.php">3.2.1 Cumulative Distribution Function</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter3/3_2_2_expectation.php">3.2.2 Expectation</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter3/3_2_3_functions_random_var.php">3.2.3 Functions of Random Variables</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter3/3_2_4_variance.php">3.2.4 Variance</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter3/3_2_5_solved3_2.php">3.2.5 Solved Problems</a></li>';
htmlText += '		</ul>';
htmlText += '		</li>';
htmlText += '		<li><a>3.3 Problems</a>';
htmlText += '		<ul>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter3/3_3_0_chapter3_problems.php">3.3.0 End of Chapter Problems</a></li>';
htmlText += '		</ul>';
htmlText += '		</li>';
htmlText += '	</ul>';
htmlText += '	</li>';
htmlText += '	<li><a>4 Continuous and Mixed Random Variables</a>';
htmlText += '	<ul>';
htmlText += '		<li><a style="text-decoration: none;" href=//www.probabilitycourse.com/chapter4/4_0_0_intro.php>4.0 Introduction</a>';
htmlText += '		</li>';
htmlText += '		<li><a>4.1 Continuous Random Variables</a>';
htmlText += '		<ul>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter4/4_1_0_continuous_random_vars_distributions.php">4.1.0 Continuous Random Variables and their Distributions</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter4/4_1_1_pdf.php">4.1.1 Probability Density Function</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter4/4_1_2_expected_val_variance.php">4.1.2 Expected Value and Variance</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter4/4_1_3_functions_continuous_var.php">4.1.3 Functions of Continuous Random Variables</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter4/4_1_4_solved4_1.php">4.1.4 Solved Problems</a></li>';
htmlText += '		</ul>';
htmlText += '		</li>';
htmlText += '		<li><a>4.2 Special Distributions</a>';
htmlText += '		<ul>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter4/4_2_1_uniform.php">4.2.1 Uniform Distribution</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter4/4_2_2_exponential.php">4.2.2 Exponential Distribution</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter4/4_2_3_normal.php">4.2.3 Normal (Gaussian) Distribution</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter4/4_2_4_Gamma_distribution.php">4.2.4 Gamma Distribution</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter4/4_2_5_other_distr.php">4.2.5 Other Distributions</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter4/4_2_6_solved4_2.php">4.2.6 Solved Problems</a></li>';
htmlText += '		</ul>';
htmlText += '		</li>';
htmlText += '		<li><a>4.3 Mixed Random Variables</a>';
htmlText += '		<ul>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter4/4_3_1_mixed.php">4.3.1 Mixed Random Variables</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter4/4_3_2_delta_function.php">4.3.2 Using the Delta Function</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter4/4_3_3_solved4_3.php">4.3.3 Solved Problems</a></li>';
htmlText += '		</ul>';
htmlText += '		</li>';
htmlText += '		<li><a>4.4 Problems</a>';
htmlText += '		<ul>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter4/4_4_0_chapter4_problems.php">4.4.0 End of Chapter Problems</a></li>';
htmlText += '		</ul>';
htmlText += '	</ul>';
htmlText += '	</li>';
htmlText += '	<li><a>5 Joint Distributions</a>';
htmlText += '	<ul>';
htmlText += '		<li><a>5.1 Two Discrete Random Variables</a>';
htmlText += '		<ul>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter5/5_1_0_joint_distributions.php">5.1.0 Two Random Variables</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter5/5_1_1_joint_pmf.php">5.1.1 Joint Probability Mass Function (PMF)</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter5/5_1_2_joint_cdf.php">5.1.2 Joint Cumulative Distribution Function (CDF)</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter5/5_1_3_conditioning_independence.php">5.1.3 Conditioning and Independence</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter5/5_1_4_functions_two_variables.php">5.1.4 Functions of Two Random Variables</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter5/5_1_5_conditional_expectation.php">5.1.5 Conditional Expectation</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter5/5_1_6_solved_prob.php">5.1.6 Solved Problems</a></li>';
htmlText += '		</ul>';
htmlText += '		</li>';
htmlText += '		<li><a>5.2 Two Continuous Random Variables</a>';
htmlText += '		<ul>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter5/5_2_0_continuous_vars.php">5.2.0 Two Continuous Random Variables</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter5/5_2_1_joint_pdf.php">5.2.1 Joint Probability Density Function</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter5/5_2_2_joint_cdf.php">5.2.2 Joint Cumulative Distribution Function</a></li>';
htmlText +=	'			<li><a href="//www.probabilitycourse.com/chapter5/5_2_3_conditioning_independence.php">5.2.3 Conditioning and Independence</a></li>';
htmlText +=	'			<li><a href="//www.probabilitycourse.com/chapter5/5_2_4_functions.php">5.2.4 Functions of Two Continuous Random Variables</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter5/5_2_5_solved_prob.php">5.2.5 Solved Problems</a></li>';
htmlText += '		</ul>';
htmlText += '		</li>';
htmlText += '		<li><a>5.3 More Topics</a>';
htmlText += '		<ul>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter5/5_3_1_covariance_correlation.php">5.3.1 Covariance and Correlation</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter5/5_3_2_bivariate_normal_dist.php">5.3.2 Bivariate Normal Distribution</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter5/5_3_3_solved_probs.php">5.3.3 Solved Problems</a></li>';
htmlText +=	'		</ul>';
htmlText += '		</li>';
htmlText +=	'		<li><a>5.4 Problems</a>';
htmlText +=	'		<ul>';
htmlText +=	'			<li><a href="//www.probabilitycourse.com/chapter5/5_4_0_chapter_problems.php">5.4.0 End of Chapter Problems</a></li>';
htmlText += '		</ul>';
htmlText += '		</li>';
htmlText += '	</ul>';
htmlText += '	</li>';
htmlText += '	<li><a>6 Multiple Random Variables</a>';
htmlText += '	<ul>';
htmlText += '		<li><a style="text-decoration: none;" href=//www.probabilitycourse.com/chapter6/6_0_0_intro.php>6.0 Introduction</a>';
htmlText += '		</li>';
htmlText +=	'		<li><a>6.1 Methods for More Than Two Random Variables</a>';
htmlText += '		<ul>';
/**htmlText += '			<li><a href="//www.probabilitycourse.com/chapter6/6_1_0_multiple_random_variables.php">6.1.0 Multiple Random Variables</a></li>';**/
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter6/6_1_1_joint_distributions_independence.php">6.1.1 Joint Distributions and Independence</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter6/6_1_2_sums_random_variables.php">6.1.2 Sums of Random Variables</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter6/6_1_3_moment_functions.php">6.1.3 Moment Generating Functions</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter6/6_1_4_characteristic_functions.php">6.1.4 Characteristic Functions</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter6/6_1_5_random_vectors.php">6.1.5 Random Vectors</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter6/6_1_6_solved_probs.php">6.1.6 Solved Problems</a></li>';
htmlText += '		</ul>';
htmlText += '		</li>';
htmlText += '		<li><a>6.2 Probability Bounds</a>';
htmlText += '		<ul>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter6/6_2_0_probability_bounds.php">6.2.0 Probability Bounds</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter6/6_2_1_union_bound_and_exten.php">6.2.1 Union Bound and Extension</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter6/6_2_2_markov_chebyshev_inequalities.php">6.2.2 Markov Chebyshev Inequalities</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter6/6_2_3_chernoff_bounds.php">6.2.3 Chernoff Bounds</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter6/6_2_4_cauchy_schwarz.php">6.2.4 Cauchy Schwarz Inequality</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter6/6_2_5_jensen&#39;s_inequality.php">6.2.5 Jensen&#39;s Inequality</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter6/6_2_6_solved6_2.php">6.2.6 Solved Problems</a></li>';
htmlText += '		</ul>';
htmlText += '		</li>';
htmlText +=	'		<li><a>6.3 Problems</a>';
htmlText +=	'		<ul>';
htmlText +=	'			<li><a href="//www.probabilitycourse.com/chapter6/6_3_0_chapter_problems.php">6.3.0 End of Chapter Problems</a></li>';
htmlText += '		</ul>';
htmlText +=	'		</li>';
htmlText += ' </ul>';
htmlText += ' </li>';
/**/
htmlText += '	<li><a>7 Limit Theorems and Convergence of Random Variables</a>';
/**/
htmlText += '	<ul>';
htmlText += '		<li><a style="text-decoration: none;" href=//www.probabilitycourse.com/chapter7/7_0_0_intro.php>7.0 Introduction</a>';
htmlText += '		</li>';
htmlText += '		<li><a>7.1 Limit Theorems</a>';
htmlText += '		<ul>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter7/7_1_0_limit_theorems.php">7.1.0 Limit Theorems</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter7/7_1_1_law_of_large_numbers.php">7.1.1 Law of Large Numbers</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter7/7_1_2_central_limit_theorem.php">7.1.2 Central Limit Theorem (CLT)</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter7/7_1_3_solved_probs.php">7.1.3 Solved Problems</a></li>';
htmlText += ' </ul>';
htmlText += ' </li>';
htmlText += '		<li><a>7.2 Convergence of Random Variables</a>';
htmlText += '		<ul>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter7/7_2_0_convergence_of_random_variables.php">7.2.0 Convergence of Random Variables</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter7/7_2_1_convergence_of_a_seq_of_nums.php">7.2.1 Convergence of  Sequence of Numbers</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter7/7_2_2_sequence_of_random_variables.php">7.2.2 Sequence of Random Variables</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter7/7_2_3_different_types_of_convergence_for_sequences_of_random_variables.php">7.2.3 Different Types of Convergence for Sequences of Random Variables</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter7/7_2_4_convergence_in_distribution.php">7.2.4 Convergence in Distribution</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter7/7_2_5_convergence_in_probability.php">7.2.5 Convergence in Probability</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter7/7_2_6_convergence_in_mean.php">7.2.6 Convergence in Mean</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter7/7_2_7_almost_sure_convergence.php">7.2.7 Almost Sure Convergence</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter7/7_2_8_solved_probs.php">7.2.8 Solved Problems</a></li>';
htmlText += '		</ul>';
htmlText += '		</li>';
htmlText +=	'		<li><a>7.3 Problems</a>';
htmlText +=	'		<ul>';
htmlText +=	'			<li><a href="//www.probabilitycourse.com/chapter7/7_3_0_chapter_problem.php">7.3.0 End of Chapter Problems</a></li>';
htmlText += '		</ul>';
htmlText += '		</li>';
htmlText += '		</ul>';
htmlText += '		</li>';

// Chapter 8
htmlText += '	<li><a>8 Statistical Inference I: Classical Methods</a>';
htmlText += '	<ul>';
htmlText += '		<li><a>8.1 Introduction</a>';
htmlText += '		<ul>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter8/8_1_0_intro.php">8.1.0 Introduction</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter8/8_1_1_random_sampling.php">8.1.1 Random Sampling</a></li>';
htmlText += '		</ul>';
htmlText += '		</li>';
htmlText += '		<li><a>8.2 Point Estimation</a>';
htmlText += '		<ul>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter8/8_2_0_point_estimation.php">8.2.0 Point Estimation</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter8/8_2_1_evaluating_estimators.php">8.2.1 Evaluating Estimators</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter8/8_2_2_point_estimators_for_mean_and_var.php">8.2.2 Point Estimators for Mean and Variance</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter8/8_2_3_max_likelihood_estimation.php">8.2.3 Maximum Likelihood Estimation (MLE)</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter8/8_2_4_asymptotic_probs_of_MLE.php">8.2.4 Asymptotic Properties of MLEs</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter8/8_2_5_solved_probs.php">8.2.5 Solved Problems</a></li>';
htmlText += '		</ul>';
htmlText += '		</li>';
htmlText += '		<li><a>8.3 Interval Estimation (Confidence Intervals)</a>';
htmlText += '		<ul>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter8/8_3_0_interval_estimation.php">8.3.0 Interval Estimation (Confidence Intervals)</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter8/8_3_1_gen_framework_of_int_estimation.php">8.3.1 The general framework of Interval Estimation</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter8/8_3_2_finding_interval_estimators.php">8.3.2 Finding Interval Estimators</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter8/8_3_3_confidence_intervals_for_norm_samples.php">8.3.3 Confidence Intervals for Normal Samples</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter8/8_3_4_solved_probs.php">8.3.4 Solved Problems</a></li>';
htmlText += '		</ul>';
htmlText += '		</li>';
htmlText += '		<li><a>8.4 Hypothesis Testing</a>';
htmlText += '		<ul>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter8/8_4_1_intro.php">8.4.1 Introduction</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter8/8_4_2_general_setting_definitions.php">8.4.2 General Setting and Definitions</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter8/8_4_3_hypothesis_testing_for_mean.php">8.4.3 Hypothesis Testing for the Mean</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter8/8_4_4_p_vals.php">8.4.4 P-Values</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter8/8_4_5_likelihood_ratio_tests.php">8.4.5 Likelihood Ratio Tests</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter8/8_4_6_solved_probs.php">8.4.6 Solved Problems</a></li>';
htmlText += '		</ul>';
htmlText += '		</li>';
htmlText += '		<li><a>8.5 Linear Regression</a>';
htmlText += '		<ul>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter8/8_5_0_linear_regression.php">8.5.0 Linear Regression</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter8/8_5_1_simple_linear_regression_model.php">8.5.1 Simple Linear Regression Model</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter8/8_5_2_first_method_for_finding_beta.php">8.5.2 The First Method for Finding beta</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter8/8_5_3_the_method_of_least_squares.php">8.5.3 The Method of Least Squares</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter8/8_5_4_extensions_and_issues.php">8.5.4 Extensions and Issues</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter8/8_5_5_solved_probs.php">8.5.5 Solved Problems</a></li>';
htmlText += '		</ul>';
htmlText += '		</li>';
htmlText += '		<li><a>8.6 Problems</a>';
htmlText += '		<ul>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter8/8_6_0_ch_probs.php">8.6.0 End of Chapter Problems</a></li>';
htmlText += '		</ul>';
htmlText += '		</li>';
htmlText += '	</ul>';
htmlText += '	</li>';

//Chapter 9
htmlText += '	<li><a>9 Statistical Inference II: Bayesian Inference</a>';
htmlText += '	<ul>';
htmlText += '		<li><a>9.1 Bayesian Inference</a>';
htmlText += '		<ul>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter9/9_1_0_bayesian_inference.php">9.1.0 Bayesian Inference</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter9/9_1_1_prior_and_posterior.php">9.1.1 Prior and Posterior</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter9/9_1_2_MAP_estimation.php">9.1.2 Maximum A Posteriori (MAP) Estimation</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter9/9_1_3_comparison_to_ML_estimation.php">9.1.3 Comparison to ML Estimation</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter9/9_1_4_conditional_expectation_MMSE.php">9.1.4 Conditional Expectation (MMSE)</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter9/9_1_5_mean_squared_error_MSE.php">9.1.5 Mean Squared Error (MSE)</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter9/9_1_6_linear_MMSE_estimat_of_random_vars.php">9.1.6 Linear MMSE Estimation of Random Variables</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter9/9_1_7_estimation_for_random_vectors.php">9.1.7 Estimation for Random Vectors</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter9/9_1_8_bayesian_hypothesis_testing.php">9.1.8 Bayesian Hypothesis Testing</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter9/9_1_9_bayesian_interval_estimation.php">9.1.9 Bayesian Interval Estimation</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter9/9_1_10_solved_probs.php">9.1.10 Solved Problems</a></li>';
htmlText += '		</ul>';
htmlText += '		</li>';
htmlText += '		<li><a>9.2 Problems</a>';
htmlText += '		<ul>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter9/9_2_0_ch_probs.php">9.2.0 End of Chapter Problems</a></li>';
htmlText += '		</ul>';
htmlText += '		</li>';
htmlText += '	</ul>';
htmlText += '	</li>';

//Chapter 10

htmlText += '	<li><a>10 Introduction to Random Processes</a>';
htmlText += '	<ul>';
htmlText += '		<li><a>10.1 Basic Concepts</a>';
htmlText += '		<ul>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter10/10_1_0_basic_concepts.php">10.1.0 Basic Concepts</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter10/10_1_1_PDFs_and_CDFs.php">10.1.1 PDFs and CDFs</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter10/10_1_2_mean_and_correlation_functions.php">10.1.2 Mean and Correlation Functions</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter10/10_1_3_multiple_random_processes.php">10.1.3 Multiple Random Processes</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter10/10_1_4_stationary_processes.php">10.1.4 Stationary Processes</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter10/10_1_5_gaussian_random_processes.php">10.1.5 Gaussian Random Processes </a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter10/10_1_6_solved_probs.php">10.1.6 Solved Problems</a></li>';
htmlText += '		</ul>';
htmlText += '		</li>';
htmlText += '		<li><a>10.2 Processing of Random Signals</a>';
htmlText += '		<ul>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter10/10_2_0_processing_of_random_signals.php">10.2.0 Processing of Random Signals</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter10/10_2_1_power_spectral_density.php">10.2.1 Power Spectral Density</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter10/10_2_2_LTI_systems_with_random_inputs.php">10.2.2 Linear Time-Invariant (LTI) Systems with Random Inputs</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter10/10_2_3_power_in_a_frequency_band.php">10.2.3 Power in a Frequency Band</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter10/10_2_4_white_noise.php">10.2.4 White Noise</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter10/10_2_5_solved_probs.php">10.2.5 Solved Problems </a></li>';
htmlText += '		</ul>';
htmlText += '		</li>';
htmlText += '		<li><a>10.3 Problems</a>';
htmlText += '		<ul>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter10/10_3_0_ch_probs.php">10.3.0 End of Chapter Problems</a></li>';
htmlText += '		</ul>';
htmlText += '		</li>';
htmlText += '	</ul>';
htmlText += '	</li>';

//Chapter 11
htmlText += '	<li><a>11 Some Important Random Processes</a>';
htmlText += '	<ul>';
htmlText += '		<li><a>11.1 Poisson Processes</a>';
htmlText += '		<ul>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter11/11_0_0_intro.php">11.1.0 Introduction</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter11/11_1_1_counting_processes.php">11.1.1 Counting Processes</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter11/11_1_2_basic_concepts_of_the_poisson_process.php">11.1.2 Basic Concepts of the Poisson Process</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter11/11_1_3_merging_and_splitting_poisson_processes.php">11.1.3 Merging and Splitting Poisson Processes</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter11/11_1_4_nonhomogeneous_poisson_processes.php">11.1.4 Nonhomogeneous Poisson Processes</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter11/11_1_5_solved_probs.php">11.1.5 Solved Problems </a></li>';
htmlText += '		</ul>';
htmlText += '		</li>';
htmlText += '		<li><a>11.2 Discrete-Time Markov Chains</a>';
htmlText += '		<ul>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter11/11_2_1_introduction.php">11.2.1 Introduction</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter11/11_2_2_state_transition_matrix_and_diagram.php">11.2.2 State Transition Matrix and Diagram</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter11/11_2_3_probability_distributions.php">11.2.3 Probability Distributions</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter11/11_2_4_classification_of_states.php">11.2.4 Classification of States</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter11/11_2_5_using_the_law_of_total_probability_with_recursion.php">11.2.5 Using the Law of Total Probability with Recursion </a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter11/11_2_6_stationary_and_limiting_distributions.php">11.2.6 Stationary and Limiting Distributions </a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter11/11_2_7_solved_probs.php">11.2.7 Solved Problems </a></li>';
htmlText += '		</ul>';
htmlText += '		</li>';
htmlText += '		<li><a>11.3 Continuous-Time Markov Chains</a>';
htmlText += '		<ul>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter11/11_3_1_introduction.php">11.3.1 Introduction</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter11/11_3_2_stationary_and_limiting_distributions.php">11.3.2 Stationary and Limiting Distributions</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter11/11_3_3_the_generator_matrix.php">11.3.3 The Generator Matrix</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter11/11_3_4_solved_probs.php">11.3.4 Solved Problems </a></li>';
htmlText += '		</ul>';
htmlText += '		</li>';
htmlText += '		<li><a>11.4 Brownian Motion (Wiener Process)</a>';
htmlText += '		<ul>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter11/11_4_0_brownian_motion_wiener_process.php">11.4.0 Brownian Motion (Wiener Process)</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter11/11_4_1_brownian_motion_as_the_limit_of_a_symmetric_random_walk.php">11.4.1 Brownian Motion as the Limit of a Symmetric Random Walk</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter11/11_4_2_definition_and_some_properties.php">1.4.2 Definition and Some Properties</a></li>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter11/11_4_3_solved_probs.php">11.4.3 Solved Problems</a></li>';
htmlText += '		</ul>';
htmlText += '		</li>';
htmlText += '		<li><a>11.5 Problems</a>';
htmlText += '		<ul>';
htmlText += '			<li><a href="//www.probabilitycourse.com/chapter11/11_5_0_end_of_chapter_problems.php">11.5.0 End of Chapter Problems</a></li>';
htmlText += '		</ul>';
htmlText += '		</li>';
htmlText += '	</ul>';
htmlText += '	</li>';

//chapter 12
htmlText += '	<li><a STYLE="text-decoration: none;" href="//www.probabilitycourse.com/chapter12/chapter12.php">12 Introduction to Simulation Using MATLAB</a>';
htmlText += '	</li>';

//chapter 13
htmlText += '	<li><a STYLE="text-decoration: none;" href="//www.probabilitycourse.com/chapter13/chapter13.php">13 Introduction to Simulation Using R</a>';
htmlText += '	</li>';

//chapter 14
htmlText += '	<li><a STYLE="text-decoration: none;" href="//www.probabilitycourse.com/chapter14/chapter14.php">14 Introduction to Simulation Using Python</a>';
htmlText += '	</li>';

//chapter 15
htmlText += '	<li><a STYLE="text-decoration: none;" href="//www.probabilitycourse.com/chapter15/chapter15.php">15 Recursive Methods</a>';
htmlText += '	</li>';

//Appendix
htmlText += '	<li><a>Appendix</a>';
htmlText += '	<ul>';
htmlText += '		<li><a style="text-decoration: none;" href="//www.probabilitycourse.com/appendix/some_important_distributions.php">Some Important Distributions</a>';
htmlText += '		</li>';
htmlText += '		<li><a style="text-decoration: none;" href="//www.probabilitycourse.com/appendix/review_fourier_transform.php">Review of the Fourier Transform</a>';
htmlText += '		</li>';
htmlText += '	</ul>';
htmlText += '	</li>';

// Bibliography
htmlText += '	<li><a STYLE="text-decoration: none;" href="//www.probabilitycourse.com/bibliography.php">Bibliography</a>';
htmlText += '	</li>';

htmlText += '</ul>';
htmlText += '</span>';

document.write(htmlText);
