# $pdflatex = "pdflatex -file-line-error -halt-on-error -interaction=nonstopmode -synctex=1";
$pdflatex = "pdflatex -shell-escape -file-line-error -halt-on-error";

END {
  system("pdftocairo -png -rx 300 -ry 300 -singlefile main.pdf")
}
