#!/usr/bin/env bash

copy_sections_from_one_file_to_other_file /home/areo/Documents/Studium/Summaries/Logic/content/Mindmap.tex LOGICSTART LOGICEND /home/areo/Documents/Studium/Summaries/Technische_Informatik/main.tex

copy_sections_from_one_file_to_other_file /home/areo/Documents/Studium/Summaries/Beweisen/content/Mindmap.tex PROOFSTART PROOFEND /home/areo/Documents/Studium/Summaries/Technische_Informatik/main.tex
