# resources: https://github.com/qutebrowser/qutebrowser/blob/master/.github/workflows/nightly.yml
# https://github.com/JackMcKew/pyinstaller-action-windows,
# https://github.com/Nuitka/Nuitka-Action
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
# https://github.com/svenstaro/upload-release-action
# https://blog.knoldus.com/manual-trigger-in-github-actions/

name: create pdfs and pngs

on:
  workflow_dispatch:
    inputs:
      subject:
        description: 'Which document should be generated?'
        type: string
        required: true
        default: "Computer_Architecture"

jobs:
  build:
    name: Document ${{ github.event.inputs.subject }}
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout Master Branch
        uses: actions/checkout@v3
        with:
          ref: "main"

      - uses: matthejue/texlive-action-personal-copy/full@master
        with:
          run: |
            apk add make
            # apk add imagemagick
            apk add poppler-utils
            cd ./${{ github.event.inputs.subject }}
            if [[ -f ./figures/generate_pngs.sh ]]; then
              cd ./figures
              chmod +x ./generate_pngs.sh
              ./generate_pngs.sh
              cd ..
            fi
            latexmk -pdf main.tex
        # continue-on-error: true

      - name: Upload pdf of document to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.UPLOAD_TO_REPO }}
          file: ${{ github.event.inputs.subject }}/main.pdf
          asset_name: ${{ github.event.inputs.subject }}.pdf
          tag: ${{ github.ref_name }}
          overwrite: true
          body: "Document ${{ github.event.inputs.subject }}.pdf was added / updated most recently"

      - name: Upload png of document to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.UPLOAD_TO_REPO }}
          file: ${{ github.event.inputs.subject }}/main.png
          asset_name: ${{ github.event.inputs.subject }}.png
          tag: ${{ github.ref_name }}
          overwrite: true
          body: "Document ${{ github.event.inputs.subject }}.png was added / updated most recently"
