# resources: https://github.com/qutebrowser/qutebrowser/blob/master/.github/workflows/nightly.yml
# https://github.com/JackMcKew/pyinstaller-action-windows,
# https://github.com/Nuitka/Nuitka-Action
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
# https://github.com/svenstaro/upload-release-action
# https://blog.knoldus.com/manual-trigger-in-github-actions/

name: create mindmaps

on:
  workflow_dispatch:
    inputs:
      subject:
        description: 'Which mindmap should be generated?'
        type: string
        required: true
        default: "Computer_Architecture"

jobs:
  build:
    name: Mindmap ${{ github.event.inputs.subject }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Master Branch
        uses: actions/checkout@v3
        with:
          ref: "main"

      - uses: matthejue/texlive-action-personal-copy/full@master
        with:
          run: |
            apk add make
            cd ./${{ github.event.inputs.subject }}
            make Mindmap.pdf
        continue-on-error: true

      - name: Upload mindmap to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.UPLOAD_TO_REPO }}
          file: Mindmap.pdf
          asset_name: ${{ github.event.inputs.subject }}
          tag: ${{ github.ref }}
          overwrite: true
          body: "Released Mindmaps"
